name: saber_cenv
channels:
  - conda-forge
  - bioconda
  - ursky
  - defaults
dependencies:
  - python=3.7
  - joblib
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - umap-learn
  - hdbscan
  - dit # this is forcing python < 3.7
  - scikit-bio
  - metabat2
  - minimap
  - sourmash
  - tqdm
  - matplotlib
  - plotly
  - seaborn
