name: saber_cenv
channels:
  - conda-forge
  - bioconda
  - ursky
  - defaults
dependencies:
  - bbmap
  - cython
  - hdbscan
  - metabat2
  - minimap2
  - numba
  - pandas
  - perl=5
  - python=3
  - samtools
  - scikit-bio
  - scikit-learn
  - scipy
  - screed
  - seqkit
  - sourmash
  - tqdm
  - umap-learn
  - zlib
  - pip
  - dit
  - pyfastx
