name: saber_cenv
channels:
  - ursky
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - bbmap=38.18
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - curl=7.78.0
  - htslib=1.9
  - k8=0.2.5
  - kernel-headers_linux-64=3.10.0
  - krb5=1.19.2
  - ld_impl_linux-64=2.35.1
  - libcurl=7.78.0
  - libdeflate=1.2
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libnghttp2=1.46.0
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - llvm-openmp=8.0.1
  - metabat2=2.15
  - minimap2=2.17
  - mummer4=4.0.0rc1
  - ncurses=6.3
  - openjdk=10.0.2
  - openmp=8.0.1
  - openssl=1.1.1m
  - perl=5.26.2
  - pip=21.2.2
  - python=3.7.11
  - python_abi=3.7
  - readline=8.1
  - seqkit=2.1.0
  - setuptools=58.0.4
  - spades=3.15.3
  - sqlite=3.36.0
  - sysroot_linux-64=2.17
  - tk=8.6.11
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
